// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ClicktransTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void clicktrans() {
    driver.get("https://dev-1.clicktrans.pl/register-test/courier");
    driver.manage().window().setSize(new Dimension(1382, 744));
    driver.findElement(By.id("user_register_company_name")).click();
    driver.findElement(By.id("user_register_company_name")).sendKeys("Testowa");
    driver.findElement(By.id("user_register_email")).sendKeys("testowafirma2020@gmail.com");
    driver.findElement(By.id("user_register_name")).sendKeys("Tester Kowalski");
    driver.findElement(By.id("user_register_phone")).sendKeys("123456789");
    driver.findElement(By.id("user_register_plainPassword")).sendKeys("abcd1234");
    driver.findElement(By.id("user_register_settings_agreementRegulations")).click();
    driver.findElement(By.id("user_register_settings_agreementPersonalData")).click();
    driver.findElement(By.id("user_register_settings_agreementMarketing")).click();
    driver.findElement(By.id("user_register_submit")).click();
    assertThat(driver.findElement(By.cssSelector(".success")).getText(), is("OK - some registration logic is mocked"));
  }
}
